version: '3.3'

services:
  ldme-mate-sfr :
    image: "vpetcu1/ldme-mate-base:${TAG}"
    network_mode: "host"
    container_name: "${PROJECT}"
    hostname: ${PROJECT}
    restart: "no"
    environment:
    - PASSWORD=password
    - USER=desktop
    cap_add:
    - SYS_PTRACE
    stdin_open: true
    tty: true
#    ports:
#      - "24:22"
#      - "4502:4502"
#      - "80:80"
#      - "3000:3000"
#      - "4004:4000"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "./${PROJECT}/:/home/desktop/${PROJECT}/"
      - /var/run/docker.sock:/var/run/docker.sock
      - "./home/:/home/desktop"
      - "./hosts:/etc/hosts"
      - "./.init/:/home/desktop/.init"
      - "./.installProjects/:/home/desktop/.installProjects"
      - "./.bashrc/:/home/desktop/.bashrc"
      - "./.profile/:/home/desktop/.profile"
      #- "./.config/rclone/rclone.conf:/home/desktop/.config/rclone/rclone.conf"
    shm_size: '2gb'
    privileged: true
