apiVersion: apps/v1
kind: Deployment
metadata:
  name: metro-deployment
  labels:
    app: metro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metro
  template:
    metadata:
      labels:
        app: metro
    spec:
      containers:
      - name: metro
        image: vpetcu1/ldme-mate-base:22.04
        securityContext:
          capabilities:
            add:
            - SYS_PTRACE
        stdin: true
        tty: true
        ports:
        - containerPort: 22
          targetPort: 24
        - containerPort: 80
          targetPort: 80
        - containerPort: 4502
          targetPort: 4502
        - containerPort: 3000
          targetPort: 3000
        - containerPort: 4000
          targetPort: 4004
        - 
